### ISSUE TITLE
member function setVar() on null

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#17]
When I click to read a project on admin side, for example XoopsTube (wgtransifex/admin/projects.php?op=savetx&pro_id=36), I get this error:

`Error: Call to a member function setVar() on null in file /modules/wgtransifex/class/Transifex.php line 92`

Tested with **wgtransifex-1_03_RC1** and Xoops 2.5.11 Beta1 (all in english).

___

My config:

PHP: 7.4.7 
MYSQL: 5.7.30-0ubuntu0.16.04.1
XOOPS: 2.5.11-Beta1

**Comment by ggoffy** [comment]
fixed
