### ISSUE TITLE
RuntimeException Error exchange data with Transifex: file not found

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#19]
When I go to Translations tab on admin side and click to the button:

"Read this translation from Transifex"
(wgtransifex/admin/translations.php?op=readtx)

I get this error:
`Error: RuntimeException: "Error exchange data with Transifex: file not found" in file /modules/wgtransifex/class/TransifexLib.php line 328`

Tested with wgtransifex-1_03_RC1 and Xoops 2.5.11 Beta1 (all in english).
___

My config:

PHP: 7.4.7
MYSQL: 5.7.30-0ubuntu0.16.04.1
XOOPS: 2.5.11-Beta1

**Comment by cesagonchu** [comment]
Ok, I entered the language code (for me it was fr_FR) and now I don't have the error message anymore.

I think a tutorial is needed for this module.

I don't know what to enter in the fields. See picture:

![wgtransifex19](https://user-images.githubusercontent.com/4613970/88486306-1c3f6600-cf7d-11ea-830a-4cf502885f4b.png)

**Comment by ggoffy** [comment]
ok, good.

if you load test data you should have all languages already in

**Comment by cesagonchu** [comment]
No

**Comment by ggoffy** [comment]
have to test

**Comment by cesagonchu** [comment]
Where is the test data?

**Comment by cesagonchu** [comment]
In the first versions of the module, I think I have seen it before but I don't see it

**Comment by ggoffy** [comment]
goto admin/dashboard and click on "Import Sample Data (will delete ALL current data)"

**Comment by ggoffy** [comment]
![grafik](https://user-images.githubusercontent.com/7547661/88486465-f797be00-cf7d-11ea-9fcc-dbc3602a33de.png)

**Comment by ggoffy** [comment]
![grafik](https://user-images.githubusercontent.com/7547661/88486472-02525300-cf7e-11ea-9b8d-780a3b6d7e41.png)

**Comment by cesagonchu** [comment]
Oh right, it's ok now :-P
