### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wgtransifex#2]
Unable to install wgtransifex. Error(s):
Installing wgTransifex
BLOB, TEXT, GEOMETRY or JSON column 'pkg_desc' can't have a default value

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.16
mySQL Version | 8.0.16

**Comment by ggoffy** [comment]
please test

**Comment by alain01** [comment]
Ok, now i can install it ! 
TX
