### ISSUE TITLE
TransifexLib.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#43]
When I do package requests I get this error:
Error: RuntimeException: "Error exchange data with Transifex: file not found" in file /modules/wgtransifex/class/TransifexLib.php line 369

___
My Config:

Lastest module wgtransifex 1.05 RC1
PHP version 7.4.9
MYSQL version 5.7.33-0ubuntu0.16.04.1
XOOPS version is 2.5.11-Beta1
ModuleAdmin version 1.2

**Comment by alain01** [comment]
May be cause the Github API certificat changed ! 
https://github.com/XoopsModules25x/wggithub/issues/28#issuecomment-799773462

> Richard found the problem, the certificate wasn't valid anymore (milo/github-api#32)

**Comment by ggoffy** [comment]
Hi cesagonchu 

for me all is working (as far as I see)

when exactly this error does occur? where and what did you click on?

**Comment by cesagonchu** [comment]
As I said, when I do package requests.
Try on my test website, you have access rights.
I send you the pass again :)

**Comment by ggoffy** [comment]
the problem have been that some projects had outdated resources
I added cleaning to the resources reading procedure to delete these outdated resources after update
https://github.com/XoopsModules25x/wgtransifex/pull/45
