### ISSUE TITLE
Protector detects attacking actions

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#67]
When I download a package (/modules/wgtransifex/admin/packages.php), if I enter a title with an upper case, I get this message:
Protector detects attacking actions
___
My config:

XOOPS 2.5.11-Beta2 from today
wgTransifex 1.1.0 (01/02/2022) from today
Server API apache2handler
Apache/2.4.52 (Ubuntu)
PHP version 8.1.2
MySQLi extension mysqlnd 8.1.2

**Comment by ggoffy** [comment]
can't reproduce. do you use a specific word? special chars?

**Comment by cesagonchu** [comment]
No, an upper case, for example:
mymoduleFR

**Comment by ggoffy** [comment]
no problem if I do so
![image](https://user-images.githubusercontent.com/7547661/192326975-1fc675ae-7352-419d-a800-52108d5a6d8a.png)
![image](https://user-images.githubusercontent.com/7547661/192327114-d58ff3da-e7cd-4451-b76a-1dc6f19f1d3d.png)

**Comment by cesagonchu** [comment]
Same thing, I tested with the last update of your module and everything is ok. I close the topic. Thanks!

**Comment by ggoffy** [comment]
thank you for testing and reporting :)
