### ISSUE TITLE
Utility::metaKeywords()

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#68]
When I go to the home page of the module (modules/wgtransifex/), I get this message:
Error: Call to undefined method XoopsModules/Wgtransifex/Utility::metaKeywords() in file /modules/wgtransifex/index.php line 232
___
My config:

XOOPS 2.5.11-Beta2 from today
wgTransifex 1.1.0 (01/02/2022) from today
Server API apache2handler
Apache/2.4.52 (Ubuntu)
PHP version 8.1.2
MySQLi extension mysqlnd 8.1.2

**Comment by ggoffy** [comment]
hi
fixed with https://github.com/XoopsModules25x/wgtransifex/pull/69

**Comment by cesagonchu** [comment]
It works, thank you!
