### ISSUE TITLE
duplicate language french

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#70]
When I create a package, two "french" are displayed in the list (See screenshot).
The first one doesn't work, you can delete it.
The second one in the list (highlighted in blue) is working.
I don't know if this is set on Transifex or in the module.

![image](https://user-images.githubusercontent.com/4613970/192332052-207c67aa-7324-4690-bc7e-dd53a14f6531.png)

**Comment by ggoffy** [comment]
the problem cames from transifex itself:
![image](https://user-images.githubusercontent.com/7547661/192335303-5a6612d9-cd46-4771-b56b-0792e8496b93.png)
in transifex we have fr and fr_FR
some translations are done by fr, some others by fr_FR
depending on the project which you want to download the one or the other one is working

**Comment by ggoffy** [comment]
if you move the projects from fr to fr_FR I can remove fr from wgtransifex

**Comment by cesagonchu** [comment]
Yes, you can delete fr and leave fr_FR
Thank you ;)

**Comment by ggoffy** [comment]
done in wgTransifex with https://github.com/XoopsModules25x/wgtransifex/pull/71

run update then it will be deleted in module

thank you
