### ISSUE TITLE
curl_init

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wgtransifex#9]
When I click the button "Read this translation from Transifex", got this error:

`Error: Error: Call to undefined function curl_init() in file /modules/wgtransifex/class/TransifexLib.php line 297`

I think I don't have CURL activated, I don't know how to do it.
___
My config:

PHP 7.4.2
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by cesagonchu** [comment]
I added the CURL function. Problem solved.
Perhaps it should be good to add in the module, into the Configuration Check, the presence of the CURL?

**Comment by ggoffy** [comment]
and I added a check for availability of curl_init to basic checks on dashboard
